# Generated by Django 2.2.7 on 2019-11-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('substance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume', models.PositiveIntegerField()),
                ('substances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substance.Substance')),
            ],
        ),
    ]
