# Generated by Django 2.2.7 on 2020-01-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, verbose_name='Color')),
                ('max_volume', models.FloatField(verbose_name='Max volume, ml')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='CartridgeInRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(verbose_name='Order number')),
                ('percent', models.FloatField(verbose_name='Percent')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualDosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.FloatField(verbose_name='low dosage')),
                ('medium', models.FloatField(verbose_name='medium dosage')),
                ('heroic', models.FloatField(verbose_name='heroic dosage')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Amount, ml')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.TextField(blank=True, null=True, verbose_name='Description Text')),
                ('internal_name', models.CharField(max_length=50, verbose_name='Internal name')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rate')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Image name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('TERPEN', 'terpen'), ('CANABIN', 'canabinoid')], max_length=30, null=True, verbose_name='Type')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=255, verbose_name='Abbreviation')),
                ('color', models.CharField(max_length=10, verbose_name='Color')),
                ('description_text', models.TextField(blank=True, null=True, verbose_name='Description Text')),
            ],
        ),
    ]
