# Generated by Django 2.2.7 on 2020-01-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200110_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientsEntity',
            new_name='Ingredient',
        ),
    ]
